SELECT CURRENT_ROLE();

USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS WH_CAGED_XS
WITH 
WAREHOUSE_SIZE = 'XSMALL'
INITIALLY_SUSPENDED = TRUE 
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE 
MIN_CLUSTER_COUNT = 1
MAX_CLUSTER_COUNT = 3
SCALING_POLICY = STANDARD;
