-- Create file format for reading CAGED TXT files
USE ROLE ACCOUNTADMIN;
USE DATABASE CAGED;
USE SCHEMA RAW;

CREATE OR REPLACE FILE FORMAT FF_CAGED_TXT
    TYPE = 'CSV'
    FIELD_DELIMITER = ';'
    SKIP_HEADER = 1
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;
